// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _int_subtraction_HH_
#define _int_subtraction_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "int_subtraction_sbkb.h"
#include "int_subtraction_scud.h"
#include "int_subtraction_hdEe.h"
#include "int_subtraction_heOg.h"

namespace ap_rtl {

struct int_subtraction : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > a_V_dout;
    sc_in< sc_logic > a_V_empty_n;
    sc_out< sc_logic > a_V_read;
    sc_in< sc_lv<16> > b_V_dout;
    sc_in< sc_logic > b_V_empty_n;
    sc_out< sc_logic > b_V_read;
    sc_out< sc_lv<16> > c_V_din;
    sc_in< sc_logic > c_V_full_n;
    sc_out< sc_logic > c_V_write;
    sc_signal< sc_lv<16> > ap_var_for_const0;


    // Module declarations
    int_subtraction(sc_module_name name);
    SC_HAS_PROCESS(int_subtraction);

    ~int_subtraction();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    int_subtraction_sbkb<1,4,32,32>* int_subtraction_sbkb_U1;
    int_subtraction_sbkb<1,4,32,32>* int_subtraction_sbkb_U2;
    int_subtraction_scud<1,2,32,16>* int_subtraction_scud_U3;
    int_subtraction_scud<1,2,32,16>* int_subtraction_scud_U4;
    int_subtraction_hdEe<1,5,16,16,16>* int_subtraction_hdEe_U5;
    int_subtraction_heOg<1,4,16,16,16>* int_subtraction_heOg_U6;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > a_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > tmp_nbreadreq_fu_44_p3;
    sc_signal< sc_lv<1> > tmp_1_nbreadreq_fu_52_p3;
    sc_signal< sc_logic > b_V_blk_n;
    sc_signal< sc_logic > c_V_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter16;
    sc_signal< sc_lv<1> > tmp_1_reg_111;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter15_reg;
    sc_signal< bool > ap_predicate_op32_read_state2;
    sc_signal< bool > ap_predicate_op33_read_state2;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter5;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter6;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter7;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter8;
    sc_signal< bool > ap_block_state11_pp0_stage0_iter9;
    sc_signal< bool > ap_block_state12_pp0_stage0_iter10;
    sc_signal< bool > ap_block_state13_pp0_stage0_iter11;
    sc_signal< bool > ap_block_state14_pp0_stage0_iter12;
    sc_signal< bool > ap_block_state15_pp0_stage0_iter13;
    sc_signal< bool > ap_block_state16_pp0_stage0_iter14;
    sc_signal< bool > ap_block_state17_pp0_stage0_iter15;
    sc_signal< bool > ap_block_state18_pp0_stage0_iter16;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter1_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter2_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter3_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter4_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter5_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter6_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter7_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter8_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter9_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter10_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter11_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter12_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter13_reg;
    sc_signal< sc_lv<1> > tmp_1_reg_111_pp0_iter14_reg;
    sc_signal< sc_lv<16> > tmp_3_reg_115;
    sc_signal< sc_lv<16> > tmp_5_reg_120;
    sc_signal< sc_lv<32> > grp_fu_79_p1;
    sc_signal< sc_lv<32> > tmp_4_reg_135;
    sc_signal< sc_lv<32> > grp_fu_82_p1;
    sc_signal< sc_lv<32> > tmp_7_reg_140;
    sc_signal< sc_lv<16> > grp_fu_85_p1;
    sc_signal< sc_lv<16> > d_reg_145;
    sc_signal< sc_lv<16> > grp_fu_88_p1;
    sc_signal< sc_lv<16> > e_reg_150;
    sc_signal< sc_lv<16> > grp_fu_91_p2;
    sc_signal< sc_lv<16> > tmp_6_reg_155;
    sc_signal< sc_lv<16> > grp_fu_95_p2;
    sc_signal< sc_lv<16> > f_reg_160;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< bool > ap_predicate_tran2to19_state2;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter5;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter6;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter7;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter8;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter9;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter10;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter11;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter12;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter13;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter14;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter15;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<32> > grp_fu_79_p0;
    sc_signal< sc_lv<32> > grp_fu_82_p0;
    sc_signal< sc_logic > grp_fu_79_ce;
    sc_signal< sc_logic > grp_fu_82_ce;
    sc_signal< sc_logic > grp_fu_85_ce;
    sc_signal< sc_logic > grp_fu_88_ce;
    sc_signal< sc_logic > grp_fu_91_ce;
    sc_signal< sc_logic > grp_fu_95_ce;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state19;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<16> ap_const_lv16_8D1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_a_V_blk_n();
    void thread_a_V_read();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state19();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state10_pp0_stage0_iter8();
    void thread_ap_block_state11_pp0_stage0_iter9();
    void thread_ap_block_state12_pp0_stage0_iter10();
    void thread_ap_block_state13_pp0_stage0_iter11();
    void thread_ap_block_state14_pp0_stage0_iter12();
    void thread_ap_block_state15_pp0_stage0_iter13();
    void thread_ap_block_state16_pp0_stage0_iter14();
    void thread_ap_block_state17_pp0_stage0_iter15();
    void thread_ap_block_state18_pp0_stage0_iter16();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_block_state5_pp0_stage0_iter3();
    void thread_ap_block_state6_pp0_stage0_iter4();
    void thread_ap_block_state7_pp0_stage0_iter5();
    void thread_ap_block_state8_pp0_stage0_iter6();
    void thread_ap_block_state9_pp0_stage0_iter7();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_predicate_op32_read_state2();
    void thread_ap_predicate_op33_read_state2();
    void thread_ap_predicate_tran2to19_state2();
    void thread_ap_ready();
    void thread_b_V_blk_n();
    void thread_b_V_read();
    void thread_c_V_blk_n();
    void thread_c_V_din();
    void thread_c_V_write();
    void thread_grp_fu_79_ce();
    void thread_grp_fu_79_p0();
    void thread_grp_fu_82_ce();
    void thread_grp_fu_82_p0();
    void thread_grp_fu_85_ce();
    void thread_grp_fu_88_ce();
    void thread_grp_fu_91_ce();
    void thread_grp_fu_95_ce();
    void thread_tmp_1_nbreadreq_fu_52_p3();
    void thread_tmp_nbreadreq_fu_44_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
